/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  NameResolver,
  NameResolverInterface,
} from "../../../reverseRegistrar/ReverseRegistrar.sol/NameResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "setName",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class NameResolver__factory {
  static readonly abi = _abi;
  static createInterface(): NameResolverInterface {
    return new Interface(_abi) as NameResolverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NameResolver {
    return new Contract(address, _abi, runner) as unknown as NameResolver;
  }
}
