/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface DNSSECInterface extends Interface {
  getFunction(
    nameOrSignature: "rrdata" | "submitRRSet" | "submitRRSets" | "deleteRRSet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AlgorithmUpdated"
      | "DigestUpdated"
      | "NSEC3DigestUpdated"
      | "RRSetUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "rrdata",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRRSet",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRRSets",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteRRSet",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "rrdata", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRRSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRRSets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteRRSet",
    data: BytesLike
  ): Result;
}

export namespace AlgorithmUpdatedEvent {
  export type InputTuple = [id: BigNumberish, addr: AddressLike];
  export type OutputTuple = [id: bigint, addr: string];
  export interface OutputObject {
    id: bigint;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DigestUpdatedEvent {
  export type InputTuple = [id: BigNumberish, addr: AddressLike];
  export type OutputTuple = [id: bigint, addr: string];
  export interface OutputObject {
    id: bigint;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NSEC3DigestUpdatedEvent {
  export type InputTuple = [id: BigNumberish, addr: AddressLike];
  export type OutputTuple = [id: bigint, addr: string];
  export interface OutputObject {
    id: bigint;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RRSetUpdatedEvent {
  export type InputTuple = [name: BytesLike, rrset: BytesLike];
  export type OutputTuple = [name: string, rrset: string];
  export interface OutputObject {
    name: string;
    rrset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DNSSEC extends BaseContract {
  connect(runner?: ContractRunner | null): DNSSEC;
  waitForDeployment(): Promise<this>;

  interface: DNSSECInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  rrdata: TypedContractMethod<
    [dnstype: BigNumberish, name: BytesLike],
    [[bigint, bigint, string]],
    "view"
  >;

  submitRRSet: TypedContractMethod<
    [input: BytesLike, sig: BytesLike, proof: BytesLike],
    [string],
    "nonpayable"
  >;

  submitRRSets: TypedContractMethod<
    [data: BytesLike, proof: BytesLike],
    [string],
    "nonpayable"
  >;

  deleteRRSet: TypedContractMethod<
    [
      deleteType: BigNumberish,
      deleteName: BytesLike,
      nsec: BytesLike,
      sig: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "rrdata"
  ): TypedContractMethod<
    [dnstype: BigNumberish, name: BytesLike],
    [[bigint, bigint, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitRRSet"
  ): TypedContractMethod<
    [input: BytesLike, sig: BytesLike, proof: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitRRSets"
  ): TypedContractMethod<
    [data: BytesLike, proof: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteRRSet"
  ): TypedContractMethod<
    [
      deleteType: BigNumberish,
      deleteName: BytesLike,
      nsec: BytesLike,
      sig: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AlgorithmUpdated"
  ): TypedContractEvent<
    AlgorithmUpdatedEvent.InputTuple,
    AlgorithmUpdatedEvent.OutputTuple,
    AlgorithmUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DigestUpdated"
  ): TypedContractEvent<
    DigestUpdatedEvent.InputTuple,
    DigestUpdatedEvent.OutputTuple,
    DigestUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NSEC3DigestUpdated"
  ): TypedContractEvent<
    NSEC3DigestUpdatedEvent.InputTuple,
    NSEC3DigestUpdatedEvent.OutputTuple,
    NSEC3DigestUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RRSetUpdated"
  ): TypedContractEvent<
    RRSetUpdatedEvent.InputTuple,
    RRSetUpdatedEvent.OutputTuple,
    RRSetUpdatedEvent.OutputObject
  >;

  filters: {
    "AlgorithmUpdated(uint8,address)": TypedContractEvent<
      AlgorithmUpdatedEvent.InputTuple,
      AlgorithmUpdatedEvent.OutputTuple,
      AlgorithmUpdatedEvent.OutputObject
    >;
    AlgorithmUpdated: TypedContractEvent<
      AlgorithmUpdatedEvent.InputTuple,
      AlgorithmUpdatedEvent.OutputTuple,
      AlgorithmUpdatedEvent.OutputObject
    >;

    "DigestUpdated(uint8,address)": TypedContractEvent<
      DigestUpdatedEvent.InputTuple,
      DigestUpdatedEvent.OutputTuple,
      DigestUpdatedEvent.OutputObject
    >;
    DigestUpdated: TypedContractEvent<
      DigestUpdatedEvent.InputTuple,
      DigestUpdatedEvent.OutputTuple,
      DigestUpdatedEvent.OutputObject
    >;

    "NSEC3DigestUpdated(uint8,address)": TypedContractEvent<
      NSEC3DigestUpdatedEvent.InputTuple,
      NSEC3DigestUpdatedEvent.OutputTuple,
      NSEC3DigestUpdatedEvent.OutputObject
    >;
    NSEC3DigestUpdated: TypedContractEvent<
      NSEC3DigestUpdatedEvent.InputTuple,
      NSEC3DigestUpdatedEvent.OutputTuple,
      NSEC3DigestUpdatedEvent.OutputObject
    >;

    "RRSetUpdated(bytes,bytes)": TypedContractEvent<
      RRSetUpdatedEvent.InputTuple,
      RRSetUpdatedEvent.OutputTuple,
      RRSetUpdatedEvent.OutputObject
    >;
    RRSetUpdated: TypedContractEvent<
      RRSetUpdatedEvent.InputTuple,
      RRSetUpdatedEvent.OutputTuple,
      RRSetUpdatedEvent.OutputObject
    >;
  };
}
