/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  DSValue,
  DSValueInterface,
} from "../../../../ethregistrar/contracts/StablePriceOracle.sol/DSValue";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "read",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class DSValue__factory {
  static readonly abi = _abi;
  static createInterface(): DSValueInterface {
    return new Interface(_abi) as DSValueInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): DSValue {
    return new Contract(address, _abi, runner) as unknown as DSValue;
  }
}
