/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DSValue__factory } from "./DSValue__factory";
export { StablePriceOracle__factory } from "./StablePriceOracle__factory";
