/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAddrResolver } from "./IAddrResolver";
export type { IContentHashResolver } from "./IContentHashResolver";
export type { INameResolver } from "./INameResolver";
export type { ITextResolver } from "./ITextResolver";
