/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as stablePriceOracleSol from "./StablePriceOracle.sol";
export { BaseRegistrar__factory } from "./BaseRegistrar__factory";
export { BaseRegistrarImplementation__factory } from "./BaseRegistrarImplementation__factory";
export { DummyOracle__factory } from "./DummyOracle__factory";
export { ETHRegistrarController__factory } from "./ETHRegistrarController__factory";
export { Migrations__factory } from "./Migrations__factory";
export { PriceOracle__factory } from "./PriceOracle__factory";
export { SimplePriceOracle__factory } from "./SimplePriceOracle__factory";
