/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stablePriceOracleSol from "./StablePriceOracle.sol";
export type { stablePriceOracleSol };
export type { BaseRegistrar } from "./BaseRegistrar";
export type { BaseRegistrarImplementation } from "./BaseRegistrarImplementation";
export type { DummyOracle } from "./DummyOracle";
export type { ETHRegistrarController } from "./ETHRegistrarController";
export type { Migrations } from "./Migrations";
export type { PriceOracle } from "./PriceOracle";
export type { SimplePriceOracle } from "./SimplePriceOracle";
