/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TNS__factory } from "./TNS__factory";
export { TNSRegistry__factory } from "./TNSRegistry__factory";
