/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ETHRegistrarController__factory } from "./ETHRegistrarController__factory";
export { TNSRegistrarController__factory } from "./TNSRegistrarController__factory";
