/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PaymentForwarderInterface extends Interface {
  getFunction(
    nameOrSignature: "namehash" | "resolve" | "sendTo" | "tns"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PaymentForwarded"): EventFragment;

  encodeFunctionData(functionFragment: "namehash", values: [string]): string;
  encodeFunctionData(functionFragment: "resolve", values: [string]): string;
  encodeFunctionData(functionFragment: "sendTo", values: [string]): string;
  encodeFunctionData(functionFragment: "tns", values?: undefined): string;

  decodeFunctionResult(functionFragment: "namehash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tns", data: BytesLike): Result;
}

export namespace PaymentForwardedEvent {
  export type InputTuple = [
    name: string,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    name: string,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    name: string;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentForwarder extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentForwarder;
  waitForDeployment(): Promise<this>;

  interface: PaymentForwarderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  namehash: TypedContractMethod<[name: string], [string], "view">;

  resolve: TypedContractMethod<[name: string], [string], "view">;

  sendTo: TypedContractMethod<[name: string], [void], "payable">;

  tns: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "namehash"
  ): TypedContractMethod<[name: string], [string], "view">;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<[name: string], [string], "view">;
  getFunction(
    nameOrSignature: "sendTo"
  ): TypedContractMethod<[name: string], [void], "payable">;
  getFunction(
    nameOrSignature: "tns"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PaymentForwarded"
  ): TypedContractEvent<
    PaymentForwardedEvent.InputTuple,
    PaymentForwardedEvent.OutputTuple,
    PaymentForwardedEvent.OutputObject
  >;

  filters: {
    "PaymentForwarded(string,address,address,uint256)": TypedContractEvent<
      PaymentForwardedEvent.InputTuple,
      PaymentForwardedEvent.OutputTuple,
      PaymentForwardedEvent.OutputObject
    >;
    PaymentForwarded: TypedContractEvent<
      PaymentForwardedEvent.InputTuple,
      PaymentForwardedEvent.OutputTuple,
      PaymentForwardedEvent.OutputObject
    >;
  };
}
