/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INameWrapper__factory } from "./INameWrapper__factory";
export { NameWrapper__factory } from "./NameWrapper__factory";
