/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dnssecOracle from "./dnssec-oracle";
export type { dnssecOracle };
import type * as ens from "./ens";
export type { ens };
