/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface RegistrarInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptRegistrarTransfer"
      | "cancelBid"
      | "entries"
      | "eraseNode"
      | "finalizeAuction"
      | "invalidateName"
      | "newBid"
      | "releaseDeed"
      | "startAuction"
      | "startAuctions"
      | "startAuctionsAndBid"
      | "state"
      | "transfer"
      | "transferRegistrars"
      | "unsealBid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionStarted"
      | "BidRevealed"
      | "HashInvalidated"
      | "HashRegistered"
      | "HashReleased"
      | "NewBid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptRegistrarTransfer",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBid",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "entries", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "eraseNode",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAuction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invalidateName",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "newBid", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "releaseDeed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startAuction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startAuctions",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "startAuctionsAndBid",
    values: [BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "state", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRegistrars",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsealBid",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptRegistrarTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eraseNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invalidateName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseDeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startAuctionsAndBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferRegistrars",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unsealBid", data: BytesLike): Result;
}

export namespace AuctionStartedEvent {
  export type InputTuple = [hash: BytesLike, registrationDate: BigNumberish];
  export type OutputTuple = [hash: string, registrationDate: bigint];
  export interface OutputObject {
    hash: string;
    registrationDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidRevealedEvent {
  export type InputTuple = [
    hash: BytesLike,
    owner: AddressLike,
    value: BigNumberish,
    status: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    owner: string,
    value: bigint,
    status: bigint
  ];
  export interface OutputObject {
    hash: string;
    owner: string;
    value: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashInvalidatedEvent {
  export type InputTuple = [
    hash: BytesLike,
    name: string,
    value: BigNumberish,
    registrationDate: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    name: string,
    value: bigint,
    registrationDate: bigint
  ];
  export interface OutputObject {
    hash: string;
    name: string;
    value: bigint;
    registrationDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashRegisteredEvent {
  export type InputTuple = [
    hash: BytesLike,
    owner: AddressLike,
    value: BigNumberish,
    registrationDate: BigNumberish
  ];
  export type OutputTuple = [
    hash: string,
    owner: string,
    value: bigint,
    registrationDate: bigint
  ];
  export interface OutputObject {
    hash: string;
    owner: string;
    value: bigint;
    registrationDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashReleasedEvent {
  export type InputTuple = [hash: BytesLike, value: BigNumberish];
  export type OutputTuple = [hash: string, value: bigint];
  export interface OutputObject {
    hash: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewBidEvent {
  export type InputTuple = [
    hash: BytesLike,
    bidder: AddressLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [hash: string, bidder: string, deposit: bigint];
  export interface OutputObject {
    hash: string;
    bidder: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Registrar extends BaseContract {
  connect(runner?: ContractRunner | null): Registrar;
  waitForDeployment(): Promise<this>;

  interface: RegistrarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptRegistrarTransfer: TypedContractMethod<
    [hash: BytesLike, deed: AddressLike, registrationDate: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelBid: TypedContractMethod<
    [bidder: AddressLike, seal: BytesLike],
    [void],
    "nonpayable"
  >;

  entries: TypedContractMethod<
    [_hash: BytesLike],
    [[bigint, string, bigint, bigint, bigint]],
    "view"
  >;

  eraseNode: TypedContractMethod<[labels: BytesLike[]], [void], "nonpayable">;

  finalizeAuction: TypedContractMethod<
    [_hash: BytesLike],
    [void],
    "nonpayable"
  >;

  invalidateName: TypedContractMethod<
    [unhashedName: string],
    [void],
    "nonpayable"
  >;

  newBid: TypedContractMethod<[sealedBid: BytesLike], [void], "payable">;

  releaseDeed: TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;

  startAuction: TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;

  startAuctions: TypedContractMethod<
    [_hashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  startAuctionsAndBid: TypedContractMethod<
    [hashes: BytesLike[], sealedBid: BytesLike],
    [void],
    "payable"
  >;

  state: TypedContractMethod<[_hash: BytesLike], [bigint], "view">;

  transfer: TypedContractMethod<
    [_hash: BytesLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferRegistrars: TypedContractMethod<
    [_hash: BytesLike],
    [void],
    "nonpayable"
  >;

  unsealBid: TypedContractMethod<
    [_hash: BytesLike, _value: BigNumberish, _salt: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptRegistrarTransfer"
  ): TypedContractMethod<
    [hash: BytesLike, deed: AddressLike, registrationDate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelBid"
  ): TypedContractMethod<
    [bidder: AddressLike, seal: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entries"
  ): TypedContractMethod<
    [_hash: BytesLike],
    [[bigint, string, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "eraseNode"
  ): TypedContractMethod<[labels: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeAuction"
  ): TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "invalidateName"
  ): TypedContractMethod<[unhashedName: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "newBid"
  ): TypedContractMethod<[sealedBid: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "releaseDeed"
  ): TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startAuction"
  ): TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startAuctions"
  ): TypedContractMethod<[_hashes: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startAuctionsAndBid"
  ): TypedContractMethod<
    [hashes: BytesLike[], sealedBid: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[_hash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [_hash: BytesLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferRegistrars"
  ): TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unsealBid"
  ): TypedContractMethod<
    [_hash: BytesLike, _value: BigNumberish, _salt: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuctionStarted"
  ): TypedContractEvent<
    AuctionStartedEvent.InputTuple,
    AuctionStartedEvent.OutputTuple,
    AuctionStartedEvent.OutputObject
  >;
  getEvent(
    key: "BidRevealed"
  ): TypedContractEvent<
    BidRevealedEvent.InputTuple,
    BidRevealedEvent.OutputTuple,
    BidRevealedEvent.OutputObject
  >;
  getEvent(
    key: "HashInvalidated"
  ): TypedContractEvent<
    HashInvalidatedEvent.InputTuple,
    HashInvalidatedEvent.OutputTuple,
    HashInvalidatedEvent.OutputObject
  >;
  getEvent(
    key: "HashRegistered"
  ): TypedContractEvent<
    HashRegisteredEvent.InputTuple,
    HashRegisteredEvent.OutputTuple,
    HashRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "HashReleased"
  ): TypedContractEvent<
    HashReleasedEvent.InputTuple,
    HashReleasedEvent.OutputTuple,
    HashReleasedEvent.OutputObject
  >;
  getEvent(
    key: "NewBid"
  ): TypedContractEvent<
    NewBidEvent.InputTuple,
    NewBidEvent.OutputTuple,
    NewBidEvent.OutputObject
  >;

  filters: {
    "AuctionStarted(bytes32,uint256)": TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;
    AuctionStarted: TypedContractEvent<
      AuctionStartedEvent.InputTuple,
      AuctionStartedEvent.OutputTuple,
      AuctionStartedEvent.OutputObject
    >;

    "BidRevealed(bytes32,address,uint256,uint8)": TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;
    BidRevealed: TypedContractEvent<
      BidRevealedEvent.InputTuple,
      BidRevealedEvent.OutputTuple,
      BidRevealedEvent.OutputObject
    >;

    "HashInvalidated(bytes32,string,uint256,uint256)": TypedContractEvent<
      HashInvalidatedEvent.InputTuple,
      HashInvalidatedEvent.OutputTuple,
      HashInvalidatedEvent.OutputObject
    >;
    HashInvalidated: TypedContractEvent<
      HashInvalidatedEvent.InputTuple,
      HashInvalidatedEvent.OutputTuple,
      HashInvalidatedEvent.OutputObject
    >;

    "HashRegistered(bytes32,address,uint256,uint256)": TypedContractEvent<
      HashRegisteredEvent.InputTuple,
      HashRegisteredEvent.OutputTuple,
      HashRegisteredEvent.OutputObject
    >;
    HashRegistered: TypedContractEvent<
      HashRegisteredEvent.InputTuple,
      HashRegisteredEvent.OutputTuple,
      HashRegisteredEvent.OutputObject
    >;

    "HashReleased(bytes32,uint256)": TypedContractEvent<
      HashReleasedEvent.InputTuple,
      HashReleasedEvent.OutputTuple,
      HashReleasedEvent.OutputObject
    >;
    HashReleased: TypedContractEvent<
      HashReleasedEvent.InputTuple,
      HashReleasedEvent.OutputTuple,
      HashReleasedEvent.OutputObject
    >;

    "NewBid(bytes32,address,uint256)": TypedContractEvent<
      NewBidEvent.InputTuple,
      NewBidEvent.OutputTuple,
      NewBidEvent.OutputObject
    >;
    NewBid: TypedContractEvent<
      NewBidEvent.InputTuple,
      NewBidEvent.OutputTuple,
      NewBidEvent.OutputObject
    >;
  };
}
