/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAddrResolver__factory } from "./IAddrResolver__factory";
export { IContentHashResolver__factory } from "./IContentHashResolver__factory";
export { INameResolver__factory } from "./INameResolver__factory";
export { ITextResolver__factory } from "./ITextResolver__factory";
