/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RootInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "setTTL"
      | "setResolver"
      | "proveAndRegisterTLD"
      | "registrar"
      | "isOwner"
      | "ROOT_NODE"
      | "CLASS_INET"
      | "setOwner"
      | "tns"
      | "oracle"
      | "TYPE_SOA"
      | "registerTLD"
      | "setSubnodeOwner"
      | "owner"
      | "TRUST_NODE"
      | "transferOwnership"
      | "setRegistrar"
      | "TYPE_TXT"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TLDRegistered" | "RegistrarChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "setTTL",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setResolver",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proveAndRegisterTLD",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registrar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "ROOT_NODE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CLASS_INET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "tns", values?: undefined): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "TYPE_SOA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerTLD",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubnodeOwner",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TRUST_NODE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "TYPE_TXT", values?: undefined): string;

  decodeFunctionResult(functionFragment: "setTTL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveAndRegisterTLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registrar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ROOT_NODE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "CLASS_INET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tns", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TYPE_SOA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerTLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubnodeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TRUST_NODE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TYPE_TXT", data: BytesLike): Result;
}

export namespace TLDRegisteredEvent {
  export type InputTuple = [node: BytesLike, registrar: AddressLike];
  export type OutputTuple = [node: string, registrar: string];
  export interface OutputObject {
    node: string;
    registrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrarChangedEvent {
  export type InputTuple = [registrar: AddressLike];
  export type OutputTuple = [registrar: string];
  export interface OutputObject {
    registrar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Root extends BaseContract {
  connect(runner?: ContractRunner | null): Root;
  waitForDeployment(): Promise<this>;

  interface: RootInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setTTL: TypedContractMethod<
    [node: BytesLike, ttl: BigNumberish],
    [void],
    "nonpayable"
  >;

  setResolver: TypedContractMethod<
    [node: BytesLike, resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  proveAndRegisterTLD: TypedContractMethod<
    [name: BytesLike, input: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  registrar: TypedContractMethod<[], [string], "view">;

  isOwner: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  ROOT_NODE: TypedContractMethod<[], [string], "view">;

  CLASS_INET: TypedContractMethod<[], [bigint], "view">;

  setOwner: TypedContractMethod<
    [node: BytesLike, owner: AddressLike],
    [void],
    "nonpayable"
  >;

  tns: TypedContractMethod<[], [string], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  TYPE_SOA: TypedContractMethod<[], [bigint], "view">;

  registerTLD: TypedContractMethod<
    [name: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  setSubnodeOwner: TypedContractMethod<
    [label: BytesLike, owner: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  TRUST_NODE: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  setRegistrar: TypedContractMethod<
    [_registrar: AddressLike],
    [void],
    "nonpayable"
  >;

  TYPE_TXT: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setTTL"
  ): TypedContractMethod<
    [node: BytesLike, ttl: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setResolver"
  ): TypedContractMethod<
    [node: BytesLike, resolver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proveAndRegisterTLD"
  ): TypedContractMethod<
    [name: BytesLike, input: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isOwner"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "ROOT_NODE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CLASS_INET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setOwner"
  ): TypedContractMethod<
    [node: BytesLike, owner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tns"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TYPE_SOA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerTLD"
  ): TypedContractMethod<
    [name: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSubnodeOwner"
  ): TypedContractMethod<
    [label: BytesLike, owner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TRUST_NODE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRegistrar"
  ): TypedContractMethod<[_registrar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "TYPE_TXT"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "TLDRegistered"
  ): TypedContractEvent<
    TLDRegisteredEvent.InputTuple,
    TLDRegisteredEvent.OutputTuple,
    TLDRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RegistrarChanged"
  ): TypedContractEvent<
    RegistrarChangedEvent.InputTuple,
    RegistrarChangedEvent.OutputTuple,
    RegistrarChangedEvent.OutputObject
  >;

  filters: {
    "TLDRegistered(bytes32,address)": TypedContractEvent<
      TLDRegisteredEvent.InputTuple,
      TLDRegisteredEvent.OutputTuple,
      TLDRegisteredEvent.OutputObject
    >;
    TLDRegistered: TypedContractEvent<
      TLDRegisteredEvent.InputTuple,
      TLDRegisteredEvent.OutputTuple,
      TLDRegisteredEvent.OutputObject
    >;

    "RegistrarChanged(address)": TypedContractEvent<
      RegistrarChangedEvent.InputTuple,
      RegistrarChangedEvent.OutputTuple,
      RegistrarChangedEvent.OutputObject
    >;
    RegistrarChanged: TypedContractEvent<
      RegistrarChangedEvent.InputTuple,
      RegistrarChangedEvent.OutputTuple,
      RegistrarChangedEvent.OutputObject
    >;
  };
}
